version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote_api
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./api_server.py:/app/api_server.py
      - ./test_data_trim.db:/app/test_data_trim.db

  web:
    image: nginx:1.21-alpine
    container_name: quote_web
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./Quote_Sheet_V1.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
