version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./api_server.py:/app/api_server.py
      - ./test_data_trim.db:/app/test_data_trim.db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:1.21-alpine
    container_name: quote_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./quote/Quote_Sheet_V1.html:/usr/share/nginx/html/index.html
      - ./quote/Quote_Export_V1.html:/usr/share/nginx/html/Quote_Export_V1.html
      - ./quote/quote_mgnt.html:/usr/share/nginx/html/quote_mgnt.html
      - ./checklist/inspection_form.html:/usr/share/nginx/html/inspection_form.html
      - ./checklist/inspection_mgmnt.html:/usr/share/nginx/html/inspection_mgmnt.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
