version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./api_server.py:/app/api_server.py
      - ./test_data_trim.db:/app/test_data_trim.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:1.21-alpine
    container_name: quote_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Quote_Sheet_V1.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      api:
        condition: service_healthy
